apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: task-service-mysql
  labels:
    app: task-service-mysql
spec:
  selector:
    matchLabels:
      app: task-service-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: task-service-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7.22
        name: mysql
        env:
        - name: MYSQL_USER
          value: skaioskit
        - name: MYSQL_DATABASE
          value: task
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: skaioskit-task-service-mysql-root-password
              key: value
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: skaioskit-task-service-mysql-password
              key: value
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        hostPath:
          path: "${DIR}/working/mysql"
---
kind: Service
apiVersion: v1
metadata:
  name: task-service-mysql
spec:
  selector:
    app: task-service-mysql
  ports:
  - protocol: TCP
    port: 3306
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: task-service
  labels:
    app: task-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: localhost:5000/skaioskit/task-service:latest
        imagePullPolicy: Always
        command: 
        - /task
        - serve
        ports:
        - containerPort: 80
        env:
        - name: BUILD_DATETIME
          value: "${DATETIME}"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: skaioskit-jwt-secret
              key: value
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: skaioskit-task-service-mysql-password
              key: value
        volumeMounts:
        - name: log-storage
          mountPath: /logs
      volumes:
      - name: log-storage
        hostPath:
          path: "${DIR}/working/logs"
---
kind: Service
apiVersion: v1
metadata:
  name: task-service
spec:
  selector:
    app: task-service
  ports:
  - protocol: TCP
    port: 80
---
